# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PT_weight',
            field=models.CharField(max_length=20, null=True, verbose_name='PT金重'),
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Cart'),
        ),
        migrations.AddField(
            model_name='product',
            name='fushi',
            field=models.CharField(max_length=20, null=True, verbose_name='副石'),
        ),
        migrations.AddField(
            model_name='product',
            name='huohao',
            field=models.CharField(max_length=30, null=True, verbose_name='货号'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=20, null=True, verbose_name='金重'),
        ),
        migrations.AddField(
            model_name='product',
            name='zhushi',
            field=models.CharField(max_length=20, null=True, verbose_name='主石'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '禁用'), (-1, '删除')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '禁用'), (-1, '删除')], default=1),
        ),
    ]
