# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-20 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20190220_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='cut',
            field=models.CharField(default='VG', max_length=10, verbose_name='切工'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='fluorescence',
            field=models.CharField(default='TH1', max_length=10, verbose_name='荧光'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='neatness',
            field=models.CharField(default='KVH', max_length=10, verbose_name='净度'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='polish',
            field=models.CharField(default='KT', max_length=10, verbose_name='抛光'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='symmetry',
            field=models.CharField(default='N', max_length=10, verbose_name='对称'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, '禁用'), (-1, '删除'), (1, '正常')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '禁用'), (-1, '删除'), (1, '正常')], default=1),
        ),
    ]
