# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190220_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='cut',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='fluorescence',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='neatness',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='polish',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='symmetry',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(-1, '删除'), (1, '正常'), (0, '禁用')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-1, '删除'), (1, '正常'), (0, '禁用')], default=1),
        ),
    ]
