# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20190220_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='/static/upload/upload/pic5.jpg', upload_to='images', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(0, '禁用'), (-1, '删除'), (1, '正常')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '禁用'), (-1, '删除'), (1, '正常')], default=1),
        ),
    ]
