# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20190221_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='img',
            field=models.ImageField(default='/upload/upload/pic5.jpg', upload_to='headImages', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '禁用'), (-1, '删除')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '禁用'), (-1, '删除')], default=1),
        ),
    ]
