# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20190221_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='img',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(-1, '删除'), (0, '禁用'), (1, '正常')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-1, '删除'), (0, '禁用'), (1, '正常')], default=1),
        ),
    ]
