# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20190221_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(choices=[(-1, '删除'), (0, '禁用'), (1, '正常')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-1, '删除'), (0, '禁用'), (1, '正常')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='pic5.jpg', upload_to='head_images', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='img',
            field=models.ImageField(default='pic5.jpg', upload_to='headImages', verbose_name='用户头像'),
        ),
    ]
